# Site settings
title: AP CSP Create Performance Task Project Documentation Template
description: GitHub Pages Template for AP CSP
baseurl: 
url: "https://timwonderer.github.io" # Your GitHub Pages URL

# Build settings
markdown: kramdown

# GitHub-specific settings
repository: timwonderer/timwonderer.github.io
github:
  is_project_page: false # Set to false if your site is a user or organization page

# Optional settings
author: Timothy Chang
email: 

# Plugins (GitHub Pages supports a limited set of plugins)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
